/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.drill.exec.store.pcap.protocol.tlssession;

import java.nio.file.Paths;
import java.time.Instant;

import org.apache.drill.common.types.TypeProtos.MinorType;
import org.apache.drill.exec.physical.rowSet.RowSet;
import org.apache.drill.exec.physical.rowSet.RowSetBuilder;
import org.apache.drill.exec.record.metadata.SchemaBuilder;
import org.apache.drill.exec.record.metadata.TupleMetadata;
import org.apache.drill.test.ClusterFixture;
import org.apache.drill.test.ClusterTest;
import org.apache.drill.test.rowSet.RowSetComparison;
import org.junit.BeforeClass;
import org.junit.Test;

/** Query tests on decoders/tls/tls_sessions.pcapng, generated by fixtures/tls_fixtures.py. */
public class TestTlsSessionQueries extends ClusterTest {
  private static final String TABLE =
      "table(dfs.`decoders/tls/tls_sessions.pcapng` (type => 'pcapng', sessionizeTCPStreams => true)) t";

  @BeforeClass
  public static void setup() throws Exception {
    ClusterTest.startCluster(ClusterFixture.builder(dirTestWatcher));
    dirTestWatcher.copyResourceToRoot(Paths.get("decoders/"));
  }

  @Test
  public void testHandshakes() throws Exception {
    // Sessions: TLS 1.2 with a certificate chain split across segments and records, TLS 1.3,
    // plain HTTP on port 443, and a malformed ClientHello on port 8443
    String sql = "select src_port, parsed_protocol, t.parsed_data.tls.sni as sni, " +
        "t.parsed_data.tls.alpn_offered[1] as alpn_offered, t.parsed_data.tls.alpn_selected as alpn_selected, " +
        "t.parsed_data.tls.server_version as server_version, t.parsed_data.tls.cipher_suite as suite, " +
        "t.parsed_data.tls.cipher_suite_name as suite_name, t.parsed_data.tls.session_resumed as resumed, " +
        "t.parsed_data.tls.certificate_encrypted as encrypted, t.parsed_data.tls.certificate_count as cert_count, " +
        "decode_error from " + TABLE + " order by src_port";
    RowSet results = client.queryBuilder().sql(sql).rowSet();
    TupleMetadata schema = new SchemaBuilder()
        .addNullable("src_port", MinorType.INT)
        .addNullable("parsed_protocol", MinorType.VARCHAR)
        .addNullable("sni", MinorType.VARCHAR)
        .addNullable("alpn_offered", MinorType.VARCHAR)
        .addNullable("alpn_selected", MinorType.VARCHAR)
        .addNullable("server_version", MinorType.VARCHAR)
        .addNullable("suite", MinorType.INT)
        .addNullable("suite_name", MinorType.VARCHAR)
        .addNullable("resumed", MinorType.BIT)
        .addNullable("encrypted", MinorType.BIT)
        .addNullable("cert_count", MinorType.INT)
        .addNullable("decode_error", MinorType.VARCHAR)
        .buildSchema();
    RowSet expected = new RowSetBuilder(client.allocator(), schema)
        .addRow(50001, "tls", "www.example.com", "http/1.1", "h2", "TLS 1.2", 0xC02F,
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", false, false, 2, null)
        .addRow(50002, "tls", "tls13.example.org", null, null, "TLS 1.3", 0x1301,
            "TLS_AES_128_GCM_SHA256", false, true, null, null)
        .addRow(50003, null, null, null, null, null, null, null, null, null, null, null)
        .addRow(50004, "tls", null, null, null, null, null, null, null, null, null,
            "tls: malformed ClientHello: needs 1024 bytes at offset 43, has 24")
        .build();
    new RowSetComparison(expected).verifyAndClearAll(results);
  }

  @Test
  public void testCertificates() throws Exception {
    String sql = "select t.parsed_data.tls.certificates[0].subject as leaf_subject, " +
        "t.parsed_data.tls.certificates[0].issuer as leaf_issuer, " +
        "t.parsed_data.tls.certificates[0].serial as leaf_serial, " +
        "t.parsed_data.tls.certificates[0].not_after as leaf_not_after, " +
        "t.parsed_data.tls.certificates[0].subject_alt_names[2] as leaf_ip, " +
        "t.parsed_data.tls.certificates[0].public_key_bits as leaf_bits, " +
        "t.parsed_data.tls.certificates[0].sha256 as leaf_sha256, " +
        "t.parsed_data.tls.certificates[1].is_self_signed as root_self_signed, " +
        "t.parsed_data.tls.certificates[1].signature_algorithm as root_sig " +
        "from " + TABLE + " where src_port = 50001";
    RowSet results = client.queryBuilder().sql(sql).rowSet();
    TupleMetadata schema = new SchemaBuilder()
        .addNullable("leaf_subject", MinorType.VARCHAR)
        .addNullable("leaf_issuer", MinorType.VARCHAR)
        .addNullable("leaf_serial", MinorType.VARCHAR)
        .addNullable("leaf_not_after", MinorType.TIMESTAMP)
        .addNullable("leaf_ip", MinorType.VARCHAR)
        .addNullable("leaf_bits", MinorType.INT)
        .addNullable("leaf_sha256", MinorType.VARCHAR)
        .addNullable("root_self_signed", MinorType.BIT)
        .addNullable("root_sig", MinorType.VARCHAR)
        .buildSchema();
    RowSet expected = new RowSetBuilder(client.allocator(), schema)
        .addRow("CN=www.example.com,O=Example", "CN=Drill Test Root CA,O=Apache Drill", "0a1b2c3d4e5f",
            Instant.parse("2025-01-02T03:04:05Z"), "93.184.216.34", 256,
            "8fd6d21ce7848700f6b269ae48215fb340f648f38db30c42be3a6d1d01ca881a", true, "SHA256withRSA")
        .build();
    new RowSetComparison(expected).verifyAndClearAll(results);
  }
}
