#!/bin/bash
# sqlline - Script to launch SQL shell
#
# Example:
# $ ./sqlline
# sqlline> !connect jdbc:optiq:model=common/target/test-classes/donuts-model.json admin admin

# Build classpath on first call. (To force rebuild, remove .classpath.)
if [ ! -f .classpath ]; then
    (cd contrib/sqlline; mvn dependency:build-classpath -Dmdep.outputFile=../../.classpath)
fi

#exec java -Drebel.log=true -javaagent:/src/jrebel/jrebel.jar -Dlogback.configurationFile=/src/drill/sandbox/prototype/sqlparser/src/test/resources/logback.xml -cp ./:"$(cat .classpath)" sqlline.SqlLine "$@"
exec java -Xmx2G -Dlogback.configurationFile=./sqlparser/src/test/resources/logback.xml -cp ./:"$(cat .classpath)" sqlline.SqlLine --verbose=true "$@"


# End sqlline
