# Temporarily disable branch protection in order to undo a commit that was
# merged during the freeze for Drill 1.21.0. This change will be completely
# reverted with the completion of the release.
github:
  protected_branches: ~
