# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Apache Drill is a distributed MPP query layer for self describing data"
  homepage: https://drill.apache.org/
  labels:
    - drill
    - sql
    - big-data
    - java
    - hive
    - hadoop
    - jdbc
    - parquet
  
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
