/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.exec.proto.beans;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class QueryId implements Externalizable, Message<QueryId>, Schema<QueryId>
{

    public static Schema<QueryId> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static QueryId getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final QueryId DEFAULT_INSTANCE = new QueryId();

    
    private long part1;
    private long part2;

    public QueryId()
    {
        
    }

    // getters and setters

    // part1

    public long getPart1()
    {
        return part1;
    }

    public QueryId setPart1(long part1)
    {
        this.part1 = part1;
        return this;
    }

    // part2

    public long getPart2()
    {
        return part2;
    }

    public QueryId setPart2(long part2)
    {
        this.part2 = part2;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<QueryId> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public QueryId newMessage()
    {
        return new QueryId();
    }

    public Class<QueryId> typeClass()
    {
        return QueryId.class;
    }

    public String messageName()
    {
        return QueryId.class.getSimpleName();
    }

    public String messageFullName()
    {
        return QueryId.class.getName();
    }

    public boolean isInitialized(QueryId message)
    {
        return true;
    }

    public void mergeFrom(Input input, QueryId message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.part1 = input.readSFixed64();
                    break;
                case 2:
                    message.part2 = input.readSFixed64();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, QueryId message) throws IOException
    {
        if(message.part1 != 0)
            output.writeSFixed64(1, message.part1, false);

        if(message.part2 != 0)
            output.writeSFixed64(2, message.part2, false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "part1";
            case 2: return "part2";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("part1", 1);
        __fieldMap.put("part2", 2);
    }
    
}
