#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Invoke Drill using Java. Command line arguments are assumed to be
# of the form
#   -Dname=value
# and are passed to Java as JVM arguments.
#
# Environment Variables
#
#   DRILLBIT_LOG_PATH       Path to the Drillbit log file.
#                           (Set in drillbit.sh)
#   DRILLBIT_QUERY_LOG_PATH Path the the query log file.
#                           (Set in drillbit.sh)
#   DRILL_JAVA_OPTS         Optional JVM arguments such as system
#                           property overides used by both the
#                           drillbit (server) and client,
#                           set in drill-env.sh or the environment.
#   DRILLBIT_JAVA_OPTS      Optional JVM arguments specifically for
#                           the server (drillbit). Set in the
#                           environment or in the user defined
#                           drill-env.sh
#   SERVER_GC_OPTS          Set in drill-env.sh, customized by
#                           drillbit.sh.
#   CP                      Drillbit classpath set in drillbit.sh

#bin=`dirname "${BASH_SOURCE-$0}"`
#bin=`cd "$bin">/dev/null; pwd`

LOG_OPTS="-Dlog.path=$DRILLBIT_LOG_PATH -Dlog.query.path=$DRILLBIT_QUERY_LOG_PATH" 
DRILL_ALL_JAVA_OPTS="$DRILL_JAVA_OPTS $DRILLBIT_JAVA_OPTS $SERVER_GC_OPTS $@ $LOG_OPTS"

# Allows dumping of command line without running.

if [ "$DRILL_DEBUG" == "1" ]; then
  execCmd=echo
else
  execCmd=exec
fi

$execCmd $JAVA $DRILL_ALL_JAVA_OPTS -cp $CP org.apache.drill.exec.server.Drillbit
