#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Invoke Drill using Java. Command line arguments are assumed to be
# of the form
#   exec|debug
# The debug option simply prints the command line option, but does not
# run Drill. Anything else runs Drill. (Command line options passed to
# drillbit.sh are passed into this script in the args[] variable, see
# below.)
#
# Environment Variables
#
#   SERVER_LOG_GC           Set to "1" to enable Java garbage collector
#                           logging.
#   DRILL_LOG_PREFIX        Path and name prefix for log files.
#                           (Set in drill-config.sh.)
#   DRILLBIT_LOG_PATH       Path to the Drillbit log file.
#                           (Set in drill-config.sh.)
#   DRILLBIT_MAX_PROC_MEM   Optional JVM argument to enforce a cap on the
#                           total memory that a drillbit can ask the system.
#   DRILL_JAVA_OPTS         Optional JVM arguments such as system
#                           property overides used by both the
#                           drillbit (server) and client,
#                           set in drill-env.sh or the environment.
#   DRILLBIT_JAVA_OPTS      Optional JVM arguments specifically for
#                           the server (drillbit). Set in the
#                           environment or in the user defined
#                           drill-env.sh
#   SERVER_GC_OPTS          Defaults set in drill-config.sh, customized
#                           in drill-env.sh.
#   CP                      Drillbit classpath set in drill-config.sh
#   args[]                  -Dname=value arguments to pass to the JVM
#                           for per-run override of configuration options.

cmd=$1
shift

drill_rotate_log ()
{
    log=$1;
    num=5;
    if [ -n "$2" ]; then
    num=$2
    fi
    if [ -f "$log" ]; then # rotate logs
    while [ $num -gt 1 ]; do
        prev=`expr $num - 1`
        [ -f "$log.$prev" ] && mv -f "$log.$prev" "$log.$num"
        num=$prev
    done
    mv -f "$log" "$log.$num";
    fi
}

# Enable GC logging if requested.
# Note: if using YARN log dir, then no log rotation because each run under YARN
# gets a new log directory.

if [ "$SERVER_LOG_GC" == "1" ]; then
  loggc="${DRILL_LOG_PREFIX}.gc"
  SERVER_GC_OPTS="${SERVER_GC_OPTS} -Xloggc:${loggc}"
  if [ -z "$DRILL_YARN_LOG_DIR" ]; then
    drill_rotate_log $loggc
  fi
fi

logqueries="${DRILL_LOG_PREFIX}_queries.json"
LOG_OPTS="-Dlog.path=$DRILLBIT_LOG_PATH -Dlog.query.path=$logqueries"
if [ -n "$DRILL_JAVA_LIB_PATH" ]; then
  DRILL_JAVA_OPTS="$DRILL_JAVA_OPTS -Djava.library.path=$DRILL_JAVA_LIB_PATH"
fi
DRILL_ALL_JAVA_OPTS="$DRILLBIT_OPTS $DRILL_JAVA_OPTS $DRILLBIT_JAVA_OPTS $SERVER_GC_OPTS $@ $LOG_OPTS"
BITCMD="$JAVA $DRILL_ALL_JAVA_OPTS -cp $CP org.apache.drill.exec.server.Drillbit"

# The wrapper is purely for unit testing.

if [ -n "$_DRILL_WRAPPER_" ]; then
  BITCMD="$_DRILL_WRAPPER_ $BITCMD"
fi

### Checking if within Memory Limits
if [ -n "$DRILLBIT_MAX_PROC_MEM" ] ; then
  # Estimating Maximum Process Memory Allowed
  DbitMaxProcMem=`echo $DRILLBIT_MAX_PROC_MEM | tr '[A-Z]' '[a-z]'`
  # Extracting Numeric Value
  DbitMaxProcMemValue=`echo ${DbitMaxProcMem:0:${#DbitMaxProcMem}-1}`;
  if [[ "$DbitMaxProcMem" == *g ]]; then
    let MaxDrillProcMemInGB=$DbitMaxProcMemValue
  elif [[ "$DbitMaxProcMem" == *m ]]; then
    let MaxDrillProcMemInGB=$DbitMaxProcMemValue/1024
  elif [[ "$DbitMaxProcMem" == *k ]]; then
    let MaxDrillProcMemInGB=$DbitMaxProcMemValue/1024/1024
  elif [[ "$DbitMaxProcMem" == *% ]]; then
    let currentFreeMem=`cat /proc/meminfo | grep MemFree | tr ' ' '\n'| grep '[0-9]'`/1024/1024
    PercFreeMemForDrillProc=$DbitMaxProcMemValue
    if [ $PercFreeMemForDrillProc -gt 95 ] ; then
      echo "[WARN] Exceeded 95% allocation with ${PercFreeMemForDrillProc}% allocation. Capping at 95%"; PercFreeMemForDrillProc=95
    fi
    let MaxDrillProcMemInGB=$currentFreeMem*$PercFreeMemForDrillProc/100
  fi
  # Calculating sum of requested parameters
  memParamsTotal=0
  MemoryOptList="Xmx MaxDirectMemorySize ReservedCodeCacheSize MaxPermSize"
  for fltr in $MemoryOptList ; do 
    #Extract
    memParamVal=`echo $BITCMD| tr ' ' '\n' | grep $fltr | tail -1 | sed 's|Xmx|Xmx=|g'` 
    #debug:: memParam=`echo $memParamVal | tr 'A-Z' 'a-z' | cut -f1 -d=`
    memValue=`echo $memParamVal | tr 'A-Z' 'a-z' | cut -f2 -d=`
    #Convert and sum up
    if [[ "$memValue" == *m ]]; then 
    memValueInGB=`echo ${memValue:0:${#memValue}-1}/1024|bc`
    # ceiling(memValueInGB) 
    if [ `echo ${memValue:0:${#memValue}-1}%1024|bc` -gt 0 ]; then
      (( memValueInGB++ ))
    fi
    else
    memValueInGB=${memValue:0:${#memValue}-1}
    fi
    let "memParamsTotal += memValueInGB" 
  done
  echo -n ` date +%Y-%m-%d" "%H:%M:%S`"  [INFO]    ";
  if [[ "$DbitMaxProcMem" == *% ]]; then
    echo "Max Memory Permitted : "$DRILLBIT_MAX_PROC_MEM" ("$MaxDrillProcMemInGB" of "$currentFreeMem" GB free memory)"
  else
    echo "Max Memory Permitted : "$MaxDrillProcMemInGB" GB"
  fi
  # Enforce Limit if envVar defined and excess requested is excess
  if [ $MaxDrillProcMemInGB -lt $memParamsTotal ] ; then
    echo ` date +%Y-%m-%d" "%H:%M:%S`"  [ERROR]    Unable to start Drillbit due to memory constraint violations"
    echo "  Total Memory Requested : "$memParamsTotal" GB"
    echo "  Check the following settings to possibly modify (or increase the Max Memory Permitted):"
    for fltr in $MemoryOptList ; do
    echo -e "\t"`echo $BITCMD| tr ' ' '\n' | grep $fltr | tail -1`
    done
    exit 127
  elif [ $MaxDrillProcMemInGB -gt $memParamsTotal ] ; then
    let spareCapacity=$MaxDrillProcMemInGB-$memParamsTotal;
    if [ $spareCapacity -gt 0 ]; then
      echo ` date +%Y-%m-%d" "%H:%M:%S`"  [WARN]    You have an allocation of "$spareCapacity" GB that is currently unused. You can increase your existing memory configuration to use this extra memory";
    fi
  fi
fi


# Run the command (exec) or just print it (debug).
# Three options: run as a child (run), run & replace this process (exec) or
# just print the command (debug).

case $cmd in
(debug)
  echo "----------------- Environment ------------------"
  env
  echo "------------------------------------------------"
  echo "Launch command:"
  echo $BITCMD
  ;;
(*)
  exec $BITCMD
  ;;
esac

