#!/bin/bash

ARGS=();
while [ $# -gt 0 ]
do
  case "$1" in
  -q) shift;
      QUERY=$1;;
  -e) shift;
      QUERY=$1;;
  -f) shift;
      FILE=$1;;
   *) ARGS+=($1);;
  esac
  shift
done

bin=`dirname "${BASH_SOURCE-$0}"`
bin=`cd "$bin">/dev/null; pwd`

. "$bin"/drill-config.sh

if [ -z $JAVA_HOME ]
then
  JAVA=`which java`
else
  JAVA=`find $JAVA_HOME -name java`
fi

if [ -e $JAVA ]; then
  echo ""
else
  echo "Java not found."
  exit 1
fi

$JAVA -version 2>&1 | grep "version" | egrep -e "1.7" > /dev/null
if [ $? -ne 0 ]; then
  echo "Java 1.7 is required to run Apache Drill."
  exit 1
fi

# get log directory
if [ "$DRILL_LOG_DIR" = "" ]; then
  export DRILL_LOG_DIR=/var/log/drill
fi


CP=$DRILL_HOME/jars/*:$CP
CP=$DRILL_HOME/lib/*:$CP
CP=$DRILL_HOME/contrib/*:$CP

CP=$DRILL_CONF_DIR:$CP

DRILL_SHELL_JAVA_OPTS="$DRILL_SHELL_JAVA_OPTS -Dlog.path=$DRILL_LOG_DIR/sqlline.log"

if [ -n "$QUERY" ]
then
  echo $QUERY | exec $JAVA $DRILL_SHELL_JAVA_OPTS $DRILL_JAVA_OPTS -cp $CP sqlline.SqlLine "${ARGS[@]}"
elif [ -n "$FILE" ]
then
  exec $JAVA $DRILL_SHELL_JAVA_OPTS $DRILL_JAVA_OPTS -cp $CP sqlline.SqlLine "${ARGS[@]}" --run=$FILE
else
  exec $JAVA $DRILL_SHELL_JAVA_OPTS $DRILL_JAVA_OPTS -cp $CP sqlline.SqlLine "${ARGS[@]}"
fi
