#!/bin/bash

ARGS=();
while [ $# -gt 0 ]
do
  case "$1" in
  -t) shift;
      TYPE=$1;;
  -zk) shift;
      ZK=$1;;
  -f) shift;
      FILE=$1;;
   *) ARGS+=($1);;
  esac
  shift
done

bin=`dirname "${BASH_SOURCE-$0}"`
bin=`cd "$bin">/dev/null; pwd`

. "$bin"/drill-config.sh

if [ -z $JAVA_HOME ]
then
  JAVA=`which java`
else
  JAVA=`find -L $JAVA_HOME -name java | head -n 1`
fi

if [ -e $JAVA ]; then
  echo ""
else
  echo "Java not found."
  exit 1
fi

$JAVA -version 2>&1 | grep "version" | egrep -e "1.7" > /dev/null
if [ $? -ne 0 ]; then
  echo "Java 1.7 is required to run Apache Drill."
  exit 1
fi

# get log directory
if [ "$DRILL_LOG_DIR" = "" ]; then
  export DRILL_LOG_DIR=/var/log/drill
fi

CP=$DRILL_HOME/jars/*:$CP
CP=$DRILL_HOME/lib/*:$CP

CP=$DRILL_CONF_DIR:$CP

DRILL_SHELL_JAVA_OPTS="$DRILL_SHELL_JAVA_OPTS -Dlog.path=$DRILL_LOG_DIR/submitter.log"

exec $JAVA $DRILL_SHELL_JAVA_OPTS $DRILL_JAVA_OPTS -cp $CP org.apache.drill.exec.client.QuerySubmitter $FILE $TYPE $ZK
