/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Maps ISO 3166-1 alpha-2 and alpha-3 country codes to GeoJSON feature names (from world.json)
export const ISO_TO_NAME: Record<string, string> = {
  // Africa
  DZ: 'Algeria', DZA: 'Algeria',
  AO: 'Angola', AGO: 'Angola',
  BJ: 'Benin', BEN: 'Benin',
  BW: 'Botswana', BWA: 'Botswana',
  BF: 'Burkina Faso', BFA: 'Burkina Faso',
  BI: 'Burundi', BDI: 'Burundi',
  CM: 'Cameroon', CMR: 'Cameroon',
  CV: 'Cabo Verde', CPV: 'Cabo Verde',
  CF: 'Central African Republic', CAF: 'Central African Republic',
  TD: 'Chad', TCD: 'Chad',
  KM: 'Comoros', COM: 'Comoros',
  CG: 'Congo', COG: 'Congo',
  CD: 'Dem. Rep. Congo', COD: 'Dem. Rep. Congo',
  CI: "Côte d'Ivoire", CIV: "Côte d'Ivoire",
  DJ: 'Djibouti', DJI: 'Djibouti',
  EG: 'Egypt', EGY: 'Egypt',
  GQ: 'Equatorial Guinea', GNQ: 'Equatorial Guinea',
  ER: 'Eritrea', ERI: 'Eritrea',
  ET: 'Ethiopia', ETH: 'Ethiopia',
  GA: 'Gabon', GAB: 'Gabon',
  GM: 'Gambia', GMB: 'Gambia',
  GH: 'Ghana', GHA: 'Ghana',
  GN: 'Guinea', GIN: 'Guinea',
  GW: 'Guinea-Bissau', GNB: 'Guinea-Bissau',
  KE: 'Kenya', KEN: 'Kenya',
  LS: 'Lesotho', LSO: 'Lesotho',
  LR: 'Liberia', LBR: 'Liberia',
  LY: 'Libya', LBY: 'Libya',
  MG: 'Madagascar', MDG: 'Madagascar',
  MW: 'Malawi', MWI: 'Malawi',
  ML: 'Mali', MLI: 'Mali',
  MR: 'Mauritania', MRT: 'Mauritania',
  MU: 'Mauritius', MUS: 'Mauritius',
  YT: 'Mayotte', MYT: 'Mayotte',
  MA: 'Morocco', MAR: 'Morocco',
  MZ: 'Mozambique', MOZ: 'Mozambique',
  NA: 'Namibia', NAM: 'Namibia',
  NE: 'Niger', NER: 'Niger',
  NG: 'Nigeria', NGA: 'Nigeria',
  RE: 'Réunion', REU: 'Réunion',
  RW: 'Rwanda', RWA: 'Rwanda',
  SH: 'St. Helena', SHN: 'St. Helena',
  ST: 'São Tomé and Príncipe', STP: 'São Tomé and Príncipe',
  SN: 'Senegal', SEN: 'Senegal',
  SC: 'Seychelles', SYC: 'Seychelles',
  SL: 'Sierra Leone', SLE: 'Sierra Leone',
  SO: 'Somalia', SOM: 'Somalia',
  ZA: 'South Africa', ZAF: 'South Africa',
  SS: 'South Sudan', SSD: 'South Sudan',
  SD: 'Sudan', SDN: 'Sudan',
  SZ: 'Eswatini', SWZ: 'Eswatini',
  TZ: 'Tanzania', TZA: 'Tanzania',
  TG: 'Togo', TGO: 'Togo',
  TN: 'Tunisia', TUN: 'Tunisia',
  UG: 'Uganda', UGA: 'Uganda',
  ZM: 'Zambia', ZMB: 'Zambia',
  ZW: 'Zimbabwe', ZWE: 'Zimbabwe',

  // Asia
  AF: 'Afghanistan', AFG: 'Afghanistan',
  AM: 'Armenia', ARM: 'Armenia',
  AZ: 'Azerbaijan', AZE: 'Azerbaijan',
  BH: 'Bahrain', BHR: 'Bahrain',
  BD: 'Bangladesh', BGD: 'Bangladesh',
  BT: 'Bhutan', BTN: 'Bhutan',
  BN: 'Brunei', BRN: 'Brunei',
  KH: 'Cambodia', KHM: 'Cambodia',
  CN: 'China', CHN: 'China',
  GE: 'Georgia', GEO: 'Georgia',
  HK: 'Hong Kong', HKG: 'Hong Kong',
  IN: 'India', IND: 'India',
  ID: 'Indonesia', IDN: 'Indonesia',
  IR: 'Iran', IRN: 'Iran',
  IQ: 'Iraq', IRQ: 'Iraq',
  IL: 'Israel', ISR: 'Israel',
  JP: 'Japan', JPN: 'Japan',
  JO: 'Jordan', JOR: 'Jordan',
  KZ: 'Kazakhstan', KAZ: 'Kazakhstan',
  KW: 'Kuwait', KWT: 'Kuwait',
  KG: 'Kyrgyzstan', KGZ: 'Kyrgyzstan',
  LA: 'Laos', LAO: 'Laos',
  LB: 'Lebanon', LBN: 'Lebanon',
  MO: 'Macao', MAC: 'Macao',
  MY: 'Malaysia', MYS: 'Malaysia',
  MV: 'Maldives', MDV: 'Maldives',
  MN: 'Mongolia', MNG: 'Mongolia',
  MM: 'Myanmar', MMR: 'Myanmar',
  NP: 'Nepal', NPL: 'Nepal',
  KP: 'North Korea', PRK: 'North Korea',
  OM: 'Oman', OMN: 'Oman',
  PK: 'Pakistan', PAK: 'Pakistan',
  PS: 'Palestine', PSE: 'Palestine',
  PH: 'Philippines', PHL: 'Philippines',
  QA: 'Qatar', QAT: 'Qatar',
  SA: 'Saudi Arabia', SAU: 'Saudi Arabia',
  SG: 'Singapore', SGP: 'Singapore',
  KR: 'South Korea', KOR: 'South Korea',
  LK: 'Sri Lanka', LKA: 'Sri Lanka',
  SY: 'Syria', SYR: 'Syria',
  TW: 'Taiwan', TWN: 'Taiwan',
  TJ: 'Tajikistan', TJK: 'Tajikistan',
  TH: 'Thailand', THA: 'Thailand',
  TL: 'Timor-Leste', TLS: 'Timor-Leste',
  TR: 'Turkey', TUR: 'Turkey',
  TM: 'Turkmenistan', TKM: 'Turkmenistan',
  AE: 'United Arab Emirates', ARE: 'United Arab Emirates',
  UZ: 'Uzbekistan', UZB: 'Uzbekistan',
  VN: 'Vietnam', VNM: 'Vietnam',
  YE: 'Yemen', YEM: 'Yemen',

  // Europe
  AX: 'Åland Islands', ALA: 'Åland Islands',
  AL: 'Albania', ALB: 'Albania',
  AD: 'Andorra', AND: 'Andorra',
  AT: 'Austria', AUT: 'Austria',
  BY: 'Belarus', BLR: 'Belarus',
  BE: 'Belgium', BEL: 'Belgium',
  BA: 'Bosnia and Herz.', BIH: 'Bosnia and Herz.',
  BG: 'Bulgaria', BGR: 'Bulgaria',
  HR: 'Croatia', HRV: 'Croatia',
  CY: 'Cyprus', CYP: 'Cyprus',
  CZ: 'Czech Republic', CZE: 'Czech Republic',
  DK: 'Denmark', DNK: 'Denmark',
  EE: 'Estonia', EST: 'Estonia',
  FO: 'Faroe Islands', FRO: 'Faroe Islands',
  FI: 'Finland', FIN: 'Finland',
  FR: 'France', FRA: 'France',
  DE: 'Germany', DEU: 'Germany',
  GI: 'Gibraltar', GIB: 'Gibraltar',
  GR: 'Greece', GRC: 'Greece',
  HU: 'Hungary', HUN: 'Hungary',
  IS: 'Iceland', ISL: 'Iceland',
  IE: 'Ireland', IRL: 'Ireland',
  IM: 'Isle of Man', IMN: 'Isle of Man',
  IT: 'Italy', ITA: 'Italy',
  XK: 'Kosovo', XKX: 'Kosovo',
  LV: 'Latvia', LVA: 'Latvia',
  LI: 'Liechtenstein', LIE: 'Liechtenstein',
  LT: 'Lithuania', LTU: 'Lithuania',
  LU: 'Luxembourg', LUX: 'Luxembourg',
  MK: 'North Macedonia', MKD: 'North Macedonia',
  MT: 'Malta', MLT: 'Malta',
  MD: 'Moldova', MDA: 'Moldova',
  MC: 'Monaco', MCO: 'Monaco',
  ME: 'Montenegro', MNE: 'Montenegro',
  NL: 'Netherlands', NLD: 'Netherlands',
  NO: 'Norway', NOR: 'Norway',
  PL: 'Poland', POL: 'Poland',
  PT: 'Portugal', PRT: 'Portugal',
  RO: 'Romania', ROU: 'Romania',
  RU: 'Russia', RUS: 'Russia',
  SM: 'San Marino', SMR: 'San Marino',
  RS: 'Serbia', SRB: 'Serbia',
  SK: 'Slovakia', SVK: 'Slovakia',
  SI: 'Slovenia', SVN: 'Slovenia',
  ES: 'Spain', ESP: 'Spain',
  SJ: 'Svalbard and Jan Mayen', SJM: 'Svalbard and Jan Mayen',
  SE: 'Sweden', SWE: 'Sweden',
  CH: 'Switzerland', CHE: 'Switzerland',
  UA: 'Ukraine', UKR: 'Ukraine',
  GB: 'United Kingdom', GBR: 'United Kingdom',
  VA: 'Vatican City', VAT: 'Vatican City',

  // North America
  AG: 'Antigua and Barbuda', ATG: 'Antigua and Barbuda',
  BS: 'Bahamas', BHS: 'Bahamas',
  BB: 'Barbados', BRB: 'Barbados',
  BZ: 'Belize', BLZ: 'Belize',
  CA: 'Canada', CAN: 'Canada',
  CR: 'Costa Rica', CRI: 'Costa Rica',
  CU: 'Cuba', CUB: 'Cuba',
  DM: 'Dominica', DMA: 'Dominica',
  DO: 'Dominican Republic', DOM: 'Dominican Republic',
  SV: 'El Salvador', SLV: 'El Salvador',
  GL: 'Greenland', GRL: 'Greenland',
  GD: 'Grenada', GRD: 'Grenada',
  GT: 'Guatemala', GTM: 'Guatemala',
  HT: 'Haiti', HTI: 'Haiti',
  HN: 'Honduras', HND: 'Honduras',
  JM: 'Jamaica', JAM: 'Jamaica',
  MX: 'Mexico', MEX: 'Mexico',
  NI: 'Nicaragua', NIC: 'Nicaragua',
  PA: 'Panama', PAN: 'Panama',
  KN: 'St. Kitts and Nevis', KNA: 'St. Kitts and Nevis',
  LC: 'Saint Lucia', LCA: 'Saint Lucia',
  VC: 'St. Vin. and Gren.', VCT: 'St. Vin. and Gren.',
  TT: 'Trinidad and Tobago', TTO: 'Trinidad and Tobago',
  US: 'United States of America', USA: 'United States of America',

  // South America
  AR: 'Argentina', ARG: 'Argentina',
  BO: 'Bolivia', BOL: 'Bolivia',
  BR: 'Brazil', BRA: 'Brazil',
  CL: 'Chile', CHL: 'Chile',
  CO: 'Colombia', COL: 'Colombia',
  EC: 'Ecuador', ECU: 'Ecuador',
  GY: 'Guyana', GUY: 'Guyana',
  PY: 'Paraguay', PRY: 'Paraguay',
  PE: 'Peru', PER: 'Peru',
  SR: 'Suriname', SUR: 'Suriname',
  UY: 'Uruguay', URY: 'Uruguay',
  VE: 'Venezuela', VEN: 'Venezuela',

  // Oceania
  AU: 'Australia', AUS: 'Australia',
  FJ: 'Fiji', FJI: 'Fiji',
  KI: 'Kiribati', KIR: 'Kiribati',
  MH: 'Marshall Islands', MHL: 'Marshall Islands',
  FM: 'Micronesia', FSM: 'Micronesia',
  NR: 'Nauru', NRU: 'Nauru',
  NZ: 'New Zealand', NZL: 'New Zealand',
  NU: 'Niue', NIU: 'Niue',
  NF: 'Norfolk Island', NFK: 'Norfolk Island',
  MP: 'Northern Mariana Islands', MNP: 'Northern Mariana Islands',
  PW: 'Palau', PLW: 'Palau',
  PG: 'Papua New Guinea', PNG: 'Papua New Guinea',
  WS: 'Samoa', WSM: 'Samoa',
  SB: 'Solomon Islands', SLB: 'Solomon Islands',
  TO: 'Tonga', TON: 'Tonga',
  TV: 'Tuvalu', TUV: 'Tuvalu',
  VU: 'Vanuatu', VUT: 'Vanuatu',
};

/**
 * Resolves a location code (ISO alpha-2, ISO alpha-3, or country name) to a GeoJSON-compatible name.
 * ISO codes are case-insensitive. Country names pass through unchanged (graceful fallback).
 *
 * @param code - The location code to resolve (e.g., "FR", "FRA", "France")
 * @returns The GeoJSON feature name (e.g., "France"), or the original code if not found
 */
export function resolveLocationName(code: string): string {
  const upper = code.trim().toUpperCase();
  return ISO_TO_NAME[upper] ?? code;
}
